/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppServerIdRouteImport } from './routes/_app.$serverId'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppSecretsRouteImport } from './routes/_app.secrets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppServerIdIndexRouteImport } from './routes/_app.$serverId.index'
import { Route as AppServerIdFirewallRouteImport } from './routes/_app.$serverId.firewall'
import { Route as AppServerIdProjectsRouteImport } from './routes/_app.$serverId.projects'
import { Route as AppServerIdResourcesRouteImport } from './routes/_app.$serverId.resources'
import { Route as AppServerIdSettingsRouteImport } from './routes/_app.$serverId.settings'
import { Route as AppServerIdProjectsIndexRouteImport } from './routes/_app.$serverId.projects.index'
import { Route as AppServerIdProjectsProjectIdRouteImport } from './routes/_app.$serverId.projects.$projectId'
import { Route as AppServerIdProjectsProjectIdIndexRouteImport } from './routes/_app.$serverId.projects.$projectId.index'
import { Route as AppServerIdProjectsProjectIdDeploymentsRouteImport } from './routes/_app.$serverId.projects.$projectId.deployments'
import { Route as AppServerIdProjectsProjectIdResourcesRouteImport } from './routes/_app.$serverId.projects.$projectId.resources'
import { Route as AppServerIdProjectsProjectIdSettingsRouteImport } from './routes/_app.$serverId.projects.$projectId.settings'
import { Route as AppServerIdProjectsProjectIdDeploymentsIndexRouteImport } from './routes/_app.$serverId.projects.$projectId.deployments.index'
import { Route as AppServerIdProjectsProjectIdDeploymentsDeploymentIdRouteImport } from './routes/_app.$serverId.projects.$projectId.deployments.$deploymentId'
import { Route as AppServerIdProjectsProjectIdResourcesIndexRouteImport } from './routes/_app.$serverId.projects.$projectId.resources.index'
import { Route as AppServerIdProjectsProjectIdResourcesResourceIdRouteImport } from './routes/_app.$serverId.projects.$projectId.resources.$resourceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppServerIdRoute = AppServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsRoute = AppSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppServerIdIndexRoute = AppServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerIdRoute,
} as any)
const AppServerIdFirewallRoute = AppServerIdFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => AppServerIdRoute,
} as any)
const AppServerIdProjectsRoute = AppServerIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppServerIdRoute,
} as any)
const AppServerIdResourcesRoute = AppServerIdResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppServerIdRoute,
} as any)
const AppServerIdSettingsRoute = AppServerIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppServerIdRoute,
} as any)
const AppServerIdProjectsIndexRoute =
  AppServerIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServerIdProjectsRoute,
  } as any)
const AppServerIdProjectsProjectIdRoute =
  AppServerIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppServerIdProjectsRoute,
  } as any)
const AppServerIdProjectsProjectIdIndexRoute =
  AppServerIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServerIdProjectsProjectIdRoute,
  } as any)
const AppServerIdProjectsProjectIdDeploymentsRoute =
  AppServerIdProjectsProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppServerIdProjectsProjectIdRoute,
  } as any)
const AppServerIdProjectsProjectIdResourcesRoute =
  AppServerIdProjectsProjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AppServerIdProjectsProjectIdRoute,
  } as any)
const AppServerIdProjectsProjectIdSettingsRoute =
  AppServerIdProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppServerIdProjectsProjectIdRoute,
  } as any)
const AppServerIdProjectsProjectIdDeploymentsIndexRoute =
  AppServerIdProjectsProjectIdDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServerIdProjectsProjectIdDeploymentsRoute,
  } as any)
const AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute =
  AppServerIdProjectsProjectIdDeploymentsDeploymentIdRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => AppServerIdProjectsProjectIdDeploymentsRoute,
  } as any)
const AppServerIdProjectsProjectIdResourcesIndexRoute =
  AppServerIdProjectsProjectIdResourcesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServerIdProjectsProjectIdResourcesRoute,
  } as any)
const AppServerIdProjectsProjectIdResourcesResourceIdRoute =
  AppServerIdProjectsProjectIdResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AppServerIdProjectsProjectIdResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$serverId': typeof AppServerIdRouteWithChildren
  '/activity': typeof AppActivityRoute
  '/domains': typeof AppDomainsRoute
  '/secrets': typeof AppSecretsRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/$serverId/firewall': typeof AppServerIdFirewallRoute
  '/$serverId/projects': typeof AppServerIdProjectsRouteWithChildren
  '/$serverId/resources': typeof AppServerIdResourcesRoute
  '/$serverId/settings': typeof AppServerIdSettingsRoute
  '/$serverId/': typeof AppServerIdIndexRoute
  '/$serverId/projects/$projectId': typeof AppServerIdProjectsProjectIdRouteWithChildren
  '/$serverId/projects/': typeof AppServerIdProjectsIndexRoute
  '/$serverId/projects/$projectId/deployments': typeof AppServerIdProjectsProjectIdDeploymentsRouteWithChildren
  '/$serverId/projects/$projectId/resources': typeof AppServerIdProjectsProjectIdResourcesRouteWithChildren
  '/$serverId/projects/$projectId/settings': typeof AppServerIdProjectsProjectIdSettingsRoute
  '/$serverId/projects/$projectId/': typeof AppServerIdProjectsProjectIdIndexRoute
  '/$serverId/projects/$projectId/deployments/$deploymentId': typeof AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute
  '/$serverId/projects/$projectId/resources/$resourceId': typeof AppServerIdProjectsProjectIdResourcesResourceIdRoute
  '/$serverId/projects/$projectId/deployments/': typeof AppServerIdProjectsProjectIdDeploymentsIndexRoute
  '/$serverId/projects/$projectId/resources/': typeof AppServerIdProjectsProjectIdResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AppActivityRoute
  '/domains': typeof AppDomainsRoute
  '/secrets': typeof AppSecretsRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/': typeof AppIndexRoute
  '/$serverId/firewall': typeof AppServerIdFirewallRoute
  '/$serverId/resources': typeof AppServerIdResourcesRoute
  '/$serverId/settings': typeof AppServerIdSettingsRoute
  '/$serverId': typeof AppServerIdIndexRoute
  '/$serverId/projects': typeof AppServerIdProjectsIndexRoute
  '/$serverId/projects/$projectId/settings': typeof AppServerIdProjectsProjectIdSettingsRoute
  '/$serverId/projects/$projectId': typeof AppServerIdProjectsProjectIdIndexRoute
  '/$serverId/projects/$projectId/deployments/$deploymentId': typeof AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute
  '/$serverId/projects/$projectId/resources/$resourceId': typeof AppServerIdProjectsProjectIdResourcesResourceIdRoute
  '/$serverId/projects/$projectId/deployments': typeof AppServerIdProjectsProjectIdDeploymentsIndexRoute
  '/$serverId/projects/$projectId/resources': typeof AppServerIdProjectsProjectIdResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/$serverId': typeof AppServerIdRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/domains': typeof AppDomainsRoute
  '/_app/secrets': typeof AppSecretsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$serverId/firewall': typeof AppServerIdFirewallRoute
  '/_app/$serverId/projects': typeof AppServerIdProjectsRouteWithChildren
  '/_app/$serverId/resources': typeof AppServerIdResourcesRoute
  '/_app/$serverId/settings': typeof AppServerIdSettingsRoute
  '/_app/$serverId/': typeof AppServerIdIndexRoute
  '/_app/$serverId/projects/$projectId': typeof AppServerIdProjectsProjectIdRouteWithChildren
  '/_app/$serverId/projects/': typeof AppServerIdProjectsIndexRoute
  '/_app/$serverId/projects/$projectId/deployments': typeof AppServerIdProjectsProjectIdDeploymentsRouteWithChildren
  '/_app/$serverId/projects/$projectId/resources': typeof AppServerIdProjectsProjectIdResourcesRouteWithChildren
  '/_app/$serverId/projects/$projectId/settings': typeof AppServerIdProjectsProjectIdSettingsRoute
  '/_app/$serverId/projects/$projectId/': typeof AppServerIdProjectsProjectIdIndexRoute
  '/_app/$serverId/projects/$projectId/deployments/$deploymentId': typeof AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute
  '/_app/$serverId/projects/$projectId/resources/$resourceId': typeof AppServerIdProjectsProjectIdResourcesResourceIdRoute
  '/_app/$serverId/projects/$projectId/deployments/': typeof AppServerIdProjectsProjectIdDeploymentsIndexRoute
  '/_app/$serverId/projects/$projectId/resources/': typeof AppServerIdProjectsProjectIdResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serverId'
    | '/activity'
    | '/domains'
    | '/secrets'
    | '/settings'
    | '/sources'
    | '/$serverId/firewall'
    | '/$serverId/projects'
    | '/$serverId/resources'
    | '/$serverId/settings'
    | '/$serverId/'
    | '/$serverId/projects/$projectId'
    | '/$serverId/projects/'
    | '/$serverId/projects/$projectId/deployments'
    | '/$serverId/projects/$projectId/resources'
    | '/$serverId/projects/$projectId/settings'
    | '/$serverId/projects/$projectId/'
    | '/$serverId/projects/$projectId/deployments/$deploymentId'
    | '/$serverId/projects/$projectId/resources/$resourceId'
    | '/$serverId/projects/$projectId/deployments/'
    | '/$serverId/projects/$projectId/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/domains'
    | '/secrets'
    | '/settings'
    | '/sources'
    | '/'
    | '/$serverId/firewall'
    | '/$serverId/resources'
    | '/$serverId/settings'
    | '/$serverId'
    | '/$serverId/projects'
    | '/$serverId/projects/$projectId/settings'
    | '/$serverId/projects/$projectId'
    | '/$serverId/projects/$projectId/deployments/$deploymentId'
    | '/$serverId/projects/$projectId/resources/$resourceId'
    | '/$serverId/projects/$projectId/deployments'
    | '/$serverId/projects/$projectId/resources'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$serverId'
    | '/_app/activity'
    | '/_app/domains'
    | '/_app/secrets'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/'
    | '/_app/$serverId/firewall'
    | '/_app/$serverId/projects'
    | '/_app/$serverId/resources'
    | '/_app/$serverId/settings'
    | '/_app/$serverId/'
    | '/_app/$serverId/projects/$projectId'
    | '/_app/$serverId/projects/'
    | '/_app/$serverId/projects/$projectId/deployments'
    | '/_app/$serverId/projects/$projectId/resources'
    | '/_app/$serverId/projects/$projectId/settings'
    | '/_app/$serverId/projects/$projectId/'
    | '/_app/$serverId/projects/$projectId/deployments/$deploymentId'
    | '/_app/$serverId/projects/$projectId/resources/$resourceId'
    | '/_app/$serverId/projects/$projectId/deployments/'
    | '/_app/$serverId/projects/$projectId/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$serverId': {
      id: '/_app/$serverId'
      path: '/$serverId'
      fullPath: '/$serverId'
      preLoaderRoute: typeof AppServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets': {
      id: '/_app/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AppSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$serverId/': {
      id: '/_app/$serverId/'
      path: '/'
      fullPath: '/$serverId/'
      preLoaderRoute: typeof AppServerIdIndexRouteImport
      parentRoute: typeof AppServerIdRoute
    }
    '/_app/$serverId/firewall': {
      id: '/_app/$serverId/firewall'
      path: '/firewall'
      fullPath: '/$serverId/firewall'
      preLoaderRoute: typeof AppServerIdFirewallRouteImport
      parentRoute: typeof AppServerIdRoute
    }
    '/_app/$serverId/projects': {
      id: '/_app/$serverId/projects'
      path: '/projects'
      fullPath: '/$serverId/projects'
      preLoaderRoute: typeof AppServerIdProjectsRouteImport
      parentRoute: typeof AppServerIdRoute
    }
    '/_app/$serverId/resources': {
      id: '/_app/$serverId/resources'
      path: '/resources'
      fullPath: '/$serverId/resources'
      preLoaderRoute: typeof AppServerIdResourcesRouteImport
      parentRoute: typeof AppServerIdRoute
    }
    '/_app/$serverId/settings': {
      id: '/_app/$serverId/settings'
      path: '/settings'
      fullPath: '/$serverId/settings'
      preLoaderRoute: typeof AppServerIdSettingsRouteImport
      parentRoute: typeof AppServerIdRoute
    }
    '/_app/$serverId/projects/': {
      id: '/_app/$serverId/projects/'
      path: '/'
      fullPath: '/$serverId/projects/'
      preLoaderRoute: typeof AppServerIdProjectsIndexRouteImport
      parentRoute: typeof AppServerIdProjectsRoute
    }
    '/_app/$serverId/projects/$projectId': {
      id: '/_app/$serverId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/$serverId/projects/$projectId'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdRouteImport
      parentRoute: typeof AppServerIdProjectsRoute
    }
    '/_app/$serverId/projects/$projectId/': {
      id: '/_app/$serverId/projects/$projectId/'
      path: '/'
      fullPath: '/$serverId/projects/$projectId/'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdRoute
    }
    '/_app/$serverId/projects/$projectId/deployments': {
      id: '/_app/$serverId/projects/$projectId/deployments'
      path: '/deployments'
      fullPath: '/$serverId/projects/$projectId/deployments'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdDeploymentsRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdRoute
    }
    '/_app/$serverId/projects/$projectId/resources': {
      id: '/_app/$serverId/projects/$projectId/resources'
      path: '/resources'
      fullPath: '/$serverId/projects/$projectId/resources'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdResourcesRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdRoute
    }
    '/_app/$serverId/projects/$projectId/settings': {
      id: '/_app/$serverId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/$serverId/projects/$projectId/settings'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdRoute
    }
    '/_app/$serverId/projects/$projectId/deployments/': {
      id: '/_app/$serverId/projects/$projectId/deployments/'
      path: '/'
      fullPath: '/$serverId/projects/$projectId/deployments/'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdDeploymentsIndexRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdDeploymentsRoute
    }
    '/_app/$serverId/projects/$projectId/deployments/$deploymentId': {
      id: '/_app/$serverId/projects/$projectId/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/$serverId/projects/$projectId/deployments/$deploymentId'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdDeploymentsRoute
    }
    '/_app/$serverId/projects/$projectId/resources/': {
      id: '/_app/$serverId/projects/$projectId/resources/'
      path: '/'
      fullPath: '/$serverId/projects/$projectId/resources/'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdResourcesIndexRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdResourcesRoute
    }
    '/_app/$serverId/projects/$projectId/resources/$resourceId': {
      id: '/_app/$serverId/projects/$projectId/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/$serverId/projects/$projectId/resources/$resourceId'
      preLoaderRoute: typeof AppServerIdProjectsProjectIdResourcesResourceIdRouteImport
      parentRoute: typeof AppServerIdProjectsProjectIdResourcesRoute
    }
  }
}

interface AppServerIdProjectsProjectIdDeploymentsRouteChildren {
  AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute: typeof AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute
  AppServerIdProjectsProjectIdDeploymentsIndexRoute: typeof AppServerIdProjectsProjectIdDeploymentsIndexRoute
}

const AppServerIdProjectsProjectIdDeploymentsRouteChildren: AppServerIdProjectsProjectIdDeploymentsRouteChildren =
  {
    AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute:
      AppServerIdProjectsProjectIdDeploymentsDeploymentIdRoute,
    AppServerIdProjectsProjectIdDeploymentsIndexRoute:
      AppServerIdProjectsProjectIdDeploymentsIndexRoute,
  }

const AppServerIdProjectsProjectIdDeploymentsRouteWithChildren =
  AppServerIdProjectsProjectIdDeploymentsRoute._addFileChildren(
    AppServerIdProjectsProjectIdDeploymentsRouteChildren,
  )

interface AppServerIdProjectsProjectIdResourcesRouteChildren {
  AppServerIdProjectsProjectIdResourcesResourceIdRoute: typeof AppServerIdProjectsProjectIdResourcesResourceIdRoute
  AppServerIdProjectsProjectIdResourcesIndexRoute: typeof AppServerIdProjectsProjectIdResourcesIndexRoute
}

const AppServerIdProjectsProjectIdResourcesRouteChildren: AppServerIdProjectsProjectIdResourcesRouteChildren =
  {
    AppServerIdProjectsProjectIdResourcesResourceIdRoute:
      AppServerIdProjectsProjectIdResourcesResourceIdRoute,
    AppServerIdProjectsProjectIdResourcesIndexRoute:
      AppServerIdProjectsProjectIdResourcesIndexRoute,
  }

const AppServerIdProjectsProjectIdResourcesRouteWithChildren =
  AppServerIdProjectsProjectIdResourcesRoute._addFileChildren(
    AppServerIdProjectsProjectIdResourcesRouteChildren,
  )

interface AppServerIdProjectsProjectIdRouteChildren {
  AppServerIdProjectsProjectIdDeploymentsRoute: typeof AppServerIdProjectsProjectIdDeploymentsRouteWithChildren
  AppServerIdProjectsProjectIdResourcesRoute: typeof AppServerIdProjectsProjectIdResourcesRouteWithChildren
  AppServerIdProjectsProjectIdSettingsRoute: typeof AppServerIdProjectsProjectIdSettingsRoute
  AppServerIdProjectsProjectIdIndexRoute: typeof AppServerIdProjectsProjectIdIndexRoute
}

const AppServerIdProjectsProjectIdRouteChildren: AppServerIdProjectsProjectIdRouteChildren =
  {
    AppServerIdProjectsProjectIdDeploymentsRoute:
      AppServerIdProjectsProjectIdDeploymentsRouteWithChildren,
    AppServerIdProjectsProjectIdResourcesRoute:
      AppServerIdProjectsProjectIdResourcesRouteWithChildren,
    AppServerIdProjectsProjectIdSettingsRoute:
      AppServerIdProjectsProjectIdSettingsRoute,
    AppServerIdProjectsProjectIdIndexRoute:
      AppServerIdProjectsProjectIdIndexRoute,
  }

const AppServerIdProjectsProjectIdRouteWithChildren =
  AppServerIdProjectsProjectIdRoute._addFileChildren(
    AppServerIdProjectsProjectIdRouteChildren,
  )

interface AppServerIdProjectsRouteChildren {
  AppServerIdProjectsProjectIdRoute: typeof AppServerIdProjectsProjectIdRouteWithChildren
  AppServerIdProjectsIndexRoute: typeof AppServerIdProjectsIndexRoute
}

const AppServerIdProjectsRouteChildren: AppServerIdProjectsRouteChildren = {
  AppServerIdProjectsProjectIdRoute:
    AppServerIdProjectsProjectIdRouteWithChildren,
  AppServerIdProjectsIndexRoute: AppServerIdProjectsIndexRoute,
}

const AppServerIdProjectsRouteWithChildren =
  AppServerIdProjectsRoute._addFileChildren(AppServerIdProjectsRouteChildren)

interface AppServerIdRouteChildren {
  AppServerIdFirewallRoute: typeof AppServerIdFirewallRoute
  AppServerIdProjectsRoute: typeof AppServerIdProjectsRouteWithChildren
  AppServerIdResourcesRoute: typeof AppServerIdResourcesRoute
  AppServerIdSettingsRoute: typeof AppServerIdSettingsRoute
  AppServerIdIndexRoute: typeof AppServerIdIndexRoute
}

const AppServerIdRouteChildren: AppServerIdRouteChildren = {
  AppServerIdFirewallRoute: AppServerIdFirewallRoute,
  AppServerIdProjectsRoute: AppServerIdProjectsRouteWithChildren,
  AppServerIdResourcesRoute: AppServerIdResourcesRoute,
  AppServerIdSettingsRoute: AppServerIdSettingsRoute,
  AppServerIdIndexRoute: AppServerIdIndexRoute,
}

const AppServerIdRouteWithChildren = AppServerIdRoute._addFileChildren(
  AppServerIdRouteChildren,
)

interface AppRouteChildren {
  AppServerIdRoute: typeof AppServerIdRouteWithChildren
  AppActivityRoute: typeof AppActivityRoute
  AppDomainsRoute: typeof AppDomainsRoute
  AppSecretsRoute: typeof AppSecretsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppServerIdRoute: AppServerIdRouteWithChildren,
  AppActivityRoute: AppActivityRoute,
  AppDomainsRoute: AppDomainsRoute,
  AppSecretsRoute: AppSecretsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
